[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "DSI Spotify API Assignment"
authors = [
    {name = "Stephen Petersen", email = "petersen.stephen@me.com"},
]
description = "A Python program that uses the Spotify Web API to report statistics about genres that a user likes based on the Liked Songs."
version = "0.1.0"
dependencies = ["requests, matplotlib.pyplot, yaml"]
requires-python = ">=3.11.0"
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
]

