ntfy.sh_topic: https://ntfy.sh/stephens_brs_notifier

default_save_path: figures/

plot_config:
  color: PLOT_COLOR
  title: PLOT_TITLE
  xtitle: X_AXIS_TITLE
  ytitle: Y_AXIS_TITLE
  fig_size: FIGURE_SIZE