ntfy.sh_topic: https://ntfy.sh/spotify_genre_app
plot_color: white
plot_title: Breakdown of Liked Songs by Genre
x_axis_title: Genre
y_axis_title: Number of Liked Songs
figure_size: [8, 11]
default_save_path: C:/Desktop